name: writea
description: "String Editor"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.4.3
  path: ^1.9.0
  path_provider: ^2.1.5
  equatable: ^2.0.7
  file_picker: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
